spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 305286551954-f4ac8u0fbnj00fc954t6uqgkbpvhhs2k.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - profile
              - email
          naver:
            clientId: kFIStW3lYamTt_YxdrYQ
            client-secret: W37yPm1Ih9
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: 
              - name
              - email
              - profile_image
            client-name: Naver
          kakao:
            client-id: 8c0dc41c99b55268d6a20be91f0d6a47
            client-secret: ZZJGHOMsRNpUuDYUJVntu2EXQAWWkIMX
            client-authentication-method: POST
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            # 기준이 되는 user_name 의 이름을 네이버에서는 response로 지정 (네이버 회원 조회시 반환되는 JSON 형태 때문)
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id